name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone dos2unix
        run: git clone git://git.code.sf.net/p/dos2unix/dos2unix

      - name: Build with NDK toolchain
        run: cd dos2unix/dos2unix && make CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang ENABLE_NLS= && find . -name "dos2unix" -type f

#      - name: Upload a Build Artifact
#        uses: actions/upload-artifact@v2.3.1
#        with:
#          path: 
